name: Deploy to S3

on:
  push:
    branches:
      - main

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws/aws-sdk-actions@v1
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 cp --recursive . s3://${{ secrets.AWS_S3_BUCKET }}
